### ISSUE TITLE
💩💩💩💩💩💩💩💩💩💩💩💩💩💩

### ISSUE THREAD

**Issue by ArthurKa** [wclr/ts-clean-built#7]
Totally removed uncommited `.js` files, which was part of the project. Keep up the good soft 👍👍👍👍👍👍👍👍

Why not `rm -rf .git` or `/`? Seems to be great idea.

**Comment by wclr** [comment]
It removes only `this-name.js` JS files that come along with TS `this-name.ts` files.

**Comment by ArthurKa** [comment]
![chrome_KQzqrQre9n](https://github.com/wclr/ts-clean-built/assets/16370704/907115df-b2b7-4c4f-96a9-33f4f109d6c3)

**Comment by wclr** [comment]
So, you were explicitly warned. Sorry about your troubles.

**Comment by ArthurKa** [comment]
Whoever read docs before using? Do me a favor, please, do not make shitty tools anymore.

**Comment by wclr** [comment]
Do yourself a favor, think before you do.

**Comment by ArthurKa** [comment]
💩
